# Generated by AC Compiler (AC->PY)
import sys, os, time
from typing import Final
def ac_pow(base, exp): return pow(base, exp)  # exponentiation operator ^
def ac_length(x): return len(x)  # length builtin

if __name__ == "__main__":
