// Generated by AC Compiler (AC->JS)
"use strict";

function main() {
    while (true) {
        console.log(`Hello, World!`);
        if (typeof process !== 'undefined') process.exit(0); else throw new Error('__ac_exit__');
    }
}

main();
