// Generated by AC Compiler (AC->Java)
import java.util.*;

public class Main {
    public static void main(String[] args) {
        while (true) {
            System.out.println("Hello, World!");
            System.exit(0);
        }
    }

}
