// Generated by AC Compiler (AC->C) from IR
#include <stdio.h>
#include <stdlib.h>

void add(a, b) {
    // TODO: opcode 38
    auto t0 = a + b;
    return t0;
    return;
    // TODO: opcode 39
}

int main() {
    auto add = <?>;
    printf("%s\n", "result");
    exit(0);
    return 0;
}
