// Generated by AC Compiler (AC->JS) from IR
"use strict";

function add(a, b) {
    let t0 = a + b;
    return t0;
    return;
}

(function main() {
    let result = add(5, 3);
    console.log(result);
    process.exit(0);
})();
