# Generated by AC Compiler (AC->PY)
import sys


def main():
    x = 5 * 3
    print()  # display (screen output)
    print(x)
    y = 5 * 3
    print()  # display (screen output)
    sys.exit(0)

if __name__ == "__main__":
    main()
