# Generated by AC Compiler (AC->PY)
import sys


def main():
    x = 5
    y = 10
    z = x + y * 2
    print(z)
    if z > 20:
        print("Greater than 20")
    else:
        print("Not greater than 20")
    counter = 0
    while counter < 3:
        print(counter)
        counter = counter + 1
    sys.exit(0)

if __name__ == "__main__":
    main()
