// Generated by AC Compiler (AC->JAVA) from IR
public class Main {
    public static void add(a, b) {
        var t0 = a + b;
        return t0;
        return;
    }

    public static void main(String[] args) {
        var result = add(5, 3);
        System.out.println(result);
        System.exit(0);
    }
}
