# Generated by AC Compiler (AC->PY)
import sys, os, time
from typing import Final
def ac_pow(base, exp): return pow(base, exp)  # exponentiation operator ^
def ac_length(x): return len(x)  # length builtin

if __name__ == "__main__":
    # <mainloop>
    mylist = [10,20,30,40,50]
    t_0 = ac_length(mylist)
    print(t_0)
    mystr = "Hello World"
    t_1 = ac_length(mystr)
    print(t_1)
    # <mainloop>
