# Generated by AC Compiler (AC->PY)
import sys, os, time
from typing import Final
def ac_pow(base, exp): return pow(base, exp)  # exponentiation operator ^

if __name__ == "__main__":
    # <mainloop>
    t_1 = ac_pow(2, 3)
    print(t_1)
    t_3 = ac_pow(5, 2)
    print(t_3)
    t_5 = ac_pow(3, 2)
    t_7 = ac_pow(2, t_5)
    print(t_7)
    # <mainloop>
