# Generated by AC Compiler (AC->PY) from IR
import sys

def fibonacci(n):
    t0 = n <= 1
    if t0:
        return n
    else:
        t2 = n - 1
        t1 = fibonacci(t2)
        t4 = n - 2
        t3 = fibonacci(t4)
        t5 = t1 + t3
        return t5
    return

if __name__ == "__main__":
    result = fibonacci(10)
    print(result)
    sys.exit(0)
