# Generated by AC Compiler (AC->PY)
import sys


def main():
    while True:
        x = 5  # Numeral(Pos.Int)
        y = 10  # Numeral(Pos.Int)
        z = x+y*2  # Numeral(Pos.Int)
        print(z)
        if z > 20:
            print("Greater than 20")
        else:
            print("Not greater than 20")
        counter = 0  # Numeral(Pos.Int)
        while counter < 3:
            print(counter)
            counter = counter+1  # Numeral(Pos.Int)
        sys.exit(0)

if __name__ == "__main__":
    main()
