// Generated by AC Compiler (AC->Java)
import java.util.*;

public class Main {
    public static void main(String[] args) {
        while (true) {
            System.out.println("Starting up...");
            List<Object> list = Arrays.asList("apple", "banana", "cherry");
            for (Object item : list) {
                System.out.println(item);
            }
            Object result = factorial(5);
            System.out.println(result);
            System.exit(0);
        }
    }
    public static Object factorial(Object arg) {
        int n = ((Number)arg).intValue();
        if (n == 0) {
            return 1;
        }
        else if (n == 1) {
            return 1;
        }
        else {
            return ((Number)arg).intValue()*(((Number)factorial(((Number)arg).intValue()-1)).intValue());
        }
    }

}
