// Generated by AC Compiler (AC->GO)
package main

import (
    "fmt"
    "syscall"
)

func _b(b bool) int64 { if b { return 1 }; return 0 }
func _ac_abort() { syscall.Kill(syscall.Getpid(), syscall.SIGABRT) }

func main() {
    // <mainloop>
    fmt.Println("Hello World!")
    // <mainloop>
}
