; Generated by AC Compiler (AC->ASM)
; x86-64 Linux NASM — assemble: nasm -f elf64 out.s && gcc out.o -o out

    default rel
    extern printf, exit
    global main

section .data
    _fmt_d db "%lld", 10, 0
    _fmt_s db "%s",  10, 0

section .text

main:
    push rbp
    mov rbp, rsp
    sub rsp, 256
    // <mainloop>
    lea rsi, [rel .str0]
    lea rdi, [rel _fmt_s]
    xor eax, eax
    call printf
    // <mainloop>
    xor edi, edi
    call exit

section .data
    .str0 db "Hello World!", 0
