// Generated by AC Compiler (AC->LIB)
// Compile: g++ -std=c++17 -shared -fPIC <file>.cpp -o <file>.so
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <functional>
#include <cstdio>
#include <cstdlib>
typedef long long ac_int;
typedef const char* ac_str;
#include "/home/abu/Documents/kiro projects/AC/AC/library/ilib/string-cheese/string-cheese.hpp"
// Link: g++ out.cpp -I. -L"/home/abu/Documents/kiro projects/AC/AC/library/ilib/string-cheese" -lacstring-cheese

#ifdef __cplusplus
extern "C" {
#endif
void ac_lib_init() {
    auto t_0 = stringm.getline();
    auto line = t_0;
    std::cout << line << "\n";
}
#ifdef __cplusplus
} // extern "C"
#endif
