#include "../include/ast.hpp"
#include "../include/type.hpp"
#include <string>
#include <sstream>
#include <vector>
#include <cctype>
#include <map>

class JSCodeGen {
    std::ostringstream out;
    int indentLevel = 0;
    std::map<std::string, TypePtr> varTypes;

    void emit(const std::string& line) {
        out << std::string(indentLevel * 4, ' ') << line << "\n";
    }
    void emitRaw(const std::string& line) { out << line << "\n"; }

    std::string quoteIfString(const std::string& val) {
        std::string v = val;
        while (!v.empty() && v.back() == ' ') v.pop_back();
        if (v.size() >= 2 && v.front() == '$' && v.back() == '$')
            return "`" + v.substr(1, v.size() - 2) + "`";
        return v;
    }

    std::string unwrapDollars(const std::string& s) {
        std::string result;
        for (size_t i = 0; i < s.size(); i++) {
            if (s[i] == '$') {
                size_t end = s.find('$', i + 1);
                if (end != std::string::npos) {
                    result += "`" + s.substr(i + 1, end - i - 1) + "`";
                    i = end; continue;
                }
            }
            result += s[i];
        }
        return result;
    }

    std::string translateCondition(const std::string& cond) {
        std::string r = cond;
        while (!r.empty() && r.back() == ' ') r.pop_back();
        r = unwrapDollars(r);
        for (size_t p = 0; (p = r.find("#=", p)) != std::string::npos;)
            r.replace(p, 2, "!=="), p += 3;
        // is -> === (AC equality keyword; JS strict equality)
        for (size_t p = 0; (p = r.find(" is ", p)) != std::string::npos;)
            r.replace(p, 4, " === "), p += 5;
        if (r.substr(0, 3) == "is ") r.replace(0, 3, "");
        return r;
    }

    std::string translateExpr(const std::string& expr) {
        std::string r = expr;
        while (!r.empty() && r.back() == ' ') r.pop_back();
        while (!r.empty() && r.front() == ' ') r = r.substr(1);
        r = unwrapDollars(r);
        for (size_t p = 0; (p = r.find("#=", p)) != std::string::npos;)
            r.replace(p, 2, "!=="), p += 3;
        // 1-based index: list[n] -> list[n-1]
        for (size_t p = 0; (p = r.find('[', p)) != std::string::npos;) {
            size_t end = r.find(']', p);
            if (end != std::string::npos) {
                std::string idx = r.substr(p + 1, end - p - 1);
                bool isNum = !idx.empty();
                for (char c : idx) if (!std::isdigit(c)) { isNum = false; break; }
                if (isNum) {
                    int n = std::stoi(idx);
                    r.replace(p, end - p + 1, "[" + std::to_string(n - 1) + "]");
                }
            }
            p++;
        }
        return r;
    }

    std::string parseCollectionItems(const std::string& raw) {
        std::string s = raw;
        if (s.size() >= 2 && s.front() == '$' && s.back() == '$')
            s = s.substr(1, s.size() - 2);
        std::string result, item;
        for (size_t i = 0; i <= s.size(); i++) {
            if (i == s.size() || s[i] == ',') {
                size_t a = item.find_first_not_of(' ');
                size_t b = item.find_last_not_of(' ');
                if (a != std::string::npos) {
                    std::string t = item.substr(a, b - a + 1);
                    if (!result.empty()) result += ", ";
                    bool isNum = !t.empty() && (std::isdigit(t[0]) || t[0] == '-');
                    result += isNum ? t : "\"" + t + "\"";
                }
                item.clear();
            } else item += s[i];
        }
        return result;
    }

    // Remove the last emitted closing brace line so we can chain else/else-if
    void removeLastBrace() {
        std::string cur = out.str();
        // find last line that is just whitespace + }
        size_t end = cur.rfind("}\n");
        if (end == std::string::npos) return;
        // find start of that line
        size_t start = cur.rfind('\n', end - 1);
        start = (start == std::string::npos) ? 0 : start + 1;
        out.str(cur.substr(0, start));
        out.seekp(0, std::ios::end);
    }

    void genBlock(const ASTNode& node) {
        if (node.children.empty()) return;
        for (auto& c : node.children) genNode(*c);
    }

    void genNode(const ASTNode& node) {
        switch (node.type) {

        case NodeType::Program: {
            emitRaw("// Generated by AC Compiler (AC->JS)");
            emitRaw("\"use strict\";");
            emitRaw("");
            const ASTNode* mainloopBlock = nullptr;
            for (auto& c : node.children) {
                if (c->type == NodeType::TagBlock && c->value == "mainloop")
                    mainloopBlock = c.get();
                else if (c->type == NodeType::AssignStmt && !c->attrs.empty())
                    emitRaw("let " + c->value + " = " + quoteIfString(c->attrs[0]) + ";");
            }
            emitRaw("");
            if (mainloopBlock) {
                emitRaw("(function main() {");
                indentLevel++;
                emit("while (true) {");
                indentLevel++;
                for (auto& c : mainloopBlock->children) genNode(*c);
                indentLevel--;
                emit("}");
                indentLevel--;
                emitRaw("})();");
            }
            break;
        }

        case NodeType::BackendDecl: break;
        case NodeType::UseStmt:     break;
        case NodeType::UseLibStmt:  break;
        case NodeType::SaveStmt:    break;
        case NodeType::ConfigCall:  break;
        case NodeType::ObjDecl:     break;

        case NodeType::DisplayStmt: {
            std::string val = node.value;
            if (val.size() >= 2 && val.front() == '$' && val.back() == '$')
                val = "`" + val.substr(1, val.size() - 2) + "`";
            emit("document.body.innerHTML += `<p>${" + val + "}</p>`;");
            break;
        }

        case NodeType::ForeignBlock: {
            emit("// Preposterous: Foreign code is too Foreign (if this breaks, that's on you)");
            std::istringstream ss(node.value);
            std::string ln;
            while (std::getline(ss, ln)) emit(ln);
            break;
        }

        case NodeType::KillStmt:
            emit("if (typeof process !== 'undefined') process.exit(0); else throw new Error('__ac_exit__');");
            break;

        case NodeType::RaiseStmt:
            emit("throw new Error(\"Preposterous: " + node.value + "\");");
            break;

        case NodeType::ReturnStmt:
            emit("return " + translateExpr(node.value) + ";");
            break;

        case NodeType::AssignStmt:
            if (!node.attrs.empty()) {
                std::string val = node.attrs[0];
                if (val.substr(0, 8) == "__list__") {
                    varTypes[node.value] = std::make_shared<Type>(Type::makeList());
                    emit("let " + node.value + " = [" + parseCollectionItems(val.substr(8)) + "];");
                } else if (val.substr(0, 9) == "__tuple__") {
                    varTypes[node.value] = std::make_shared<Type>(Type::makeTuple());
                    emit("const " + node.value + " = Object.freeze([" + parseCollectionItems(val.substr(9)) + "]);");
                } else if (val.substr(0, 6) == "__fn__") {
                    varTypes[node.value] = std::make_shared<Type>(Type::makeNumeral(NumeralSubtype::PosInt));
                    emit("let " + node.value + " = " + translateExpr(val.substr(6)) + ";");
                } else {
                    bool isNum = !val.empty() && (std::isdigit(val[0]) || (val[0] == '-' && val.size() > 1));
                    if (isNum) {
                        auto t = Type::inferNumeral(val);
                        varTypes[node.value] = std::make_shared<Type>(t);
                        emit("let " + node.value + " = " + val + "; // " + t.toString());
                    } else {
                        varTypes[node.value] = std::make_shared<Type>(Type::makeString());
                        emit("let " + node.value + " = " + quoteIfString(val) + ";");
                    }
                }
            }
            break;

        case NodeType::PropAssign:
            if (!node.attrs.empty())
                emit(node.value + " = " + quoteIfString(node.attrs[0]) + ";");
            break;

        case NodeType::MethodCall: {
            std::string args = node.attrs.empty() ? "" : node.attrs[0];
            if (args.size() >= 2 && args.front() == '$' && args.back() == '$')
                args = "`" + args.substr(1, args.size() - 2) + "`";
            else
                args = translateExpr(args);
            std::string name = node.value;
            if (name == "Term.display") name = "console.log";

            // display variants -> DOM injection
            if (name == "display" || name == "bold.display" || name == "italic.display" ||
                name == "title.display" || name == "header.display" || name == "link.display") {
                std::string content = args;
                std::string tag = "p";
                if (name == "bold.display")   tag = "b";
                if (name == "italic.display") tag = "i";
                if (name == "title.display")  tag = "title";
                if (name == "link.display")   tag = "a";
                if (name == "header.display") {
                    std::string level = "1";
                    if (node.attrs.size() > 1)
                        for (char c : node.attrs[1]) if (std::isdigit(c)) { level = std::string(1,c); break; }
                    tag = "h" + level;
                }
                emit("document.body.innerHTML += `<" + tag + ">${" + content + "}</" + tag + ">`;");
                break;
            }

            emit(name + "(" + args + ");");
            break;
        }

        case NodeType::FuncDef: {
            std::string arg = node.attrs.empty() ? "" : node.attrs[0];
            emit("function " + node.value + "(" + arg + ") {");
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            indentLevel--;
            emit("}");
            break;
        }

        case NodeType::IfStmt: {
            if (node.value == "OTHER") {
                removeLastBrace();
                emit("} else {");
                indentLevel++;
                if (!node.children.empty()) genBlock(*node.children[0]);
                indentLevel--;
                emit("}");
            } else {
                std::string cond = translateCondition(node.value);
                emit("if (" + cond + ") {");
                indentLevel++;
                if (!node.children.empty()) genBlock(*node.children[0]);
                indentLevel--;
                emit("}");
            }
            break;
        }

        case NodeType::ElseIfStmt: {
            std::string cond = translateCondition(node.value);
            removeLastBrace();
            emit("} else if (" + cond + ") {");
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            indentLevel--;
            emit("}");
            break;
        }

        case NodeType::ForLoop: {
            std::string lst = node.attrs.empty() ? "[]" : translateExpr(node.attrs[0]);
            emit("for (const " + node.value + " of " + lst + ") {");
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            indentLevel--;
            emit("}");
            break;
        }

        case NodeType::WhilstLoop: {
            std::string cond = translateCondition(node.value);
            emit("while (" + cond + ") {");
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            indentLevel--;
            emit("}");
            break;
        }

        case NodeType::BinaryExpr:
            emit(translateExpr(node.value) + ";");
            break;

        case NodeType::TagBlock:
            genTagBlock(node);
            break;

        case NodeType::Block:
            for (auto& c : node.children) genNode(*c);
            break;

        case NodeType::CustomTagDef:
            emit("function spawn_" + node.value + "() {");
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            indentLevel--;
            emit("}");
            break;

        case NodeType::SpawnStmt: {
            std::string name = node.value;
            std::string lower = name;
            for (auto& c : lower) c = std::tolower(c);
            emit("spawn_" + lower + "();");
            break;
        }

        case NodeType::EventListener:
        case NodeType::WhenBlock:
            for (auto& c : node.children) genNode(*c);
            break;

        default: break;
        }
    }

    void genTagBlock(const ASTNode& node) {
        std::string name = node.value;
        if (name == "mainloop") {
            emit("function main() {");
            indentLevel++;

            bool hasStartHere = false;
            for (auto& c : node.children)
                if (c->type == NodeType::TagBlock && c->value == "StartHere")
                    { hasStartHere = true; break; }

            if (hasStartHere) {
                for (auto& c : node.children) {
                    if (c->type == NodeType::TagBlock && c->value == "StartHere") break;
                    genNode(*c);
                }
                emit("while (true) {");
                indentLevel++;
                for (auto& c : node.children)
                    if (c->type == NodeType::TagBlock && c->value == "StartHere")
                        { for (auto& inner : c->children) genNode(*inner); break; }
                indentLevel--;
                emit("}");
            } else {
                emit("while (true) {");
                indentLevel++;
                for (auto& c : node.children) genNode(*c);
                indentLevel--;
                emit("}");
            }

            indentLevel--;
            emit("}");
            emitRaw("");
            emit("main();");
        } else if (name == "gui" || name == "OBJECT" || name == "SCREEN") {
            // GUI — skip
        } else if (name == "LOGIC" || name == "Local") {
            for (auto& c : node.children) genNode(*c);
        } else if (name == "StartHere") {
            emit("while (true) {");
            indentLevel++;
            for (auto& c : node.children) genNode(*c);
            indentLevel--;
            emit("}");
        } else {
            std::string lower = name;
            for (auto& c : lower) c = std::tolower(c);
            emit("spawn_" + lower + "();");
            for (auto& c : node.children) genNode(*c);
        }
    }

public:
    std::string generate(const ASTNode& node) {
        genNode(node);
        return out.str();
    }
};

std::string generateJS(const ASTNode& ast) {
    JSCodeGen gen;
    return gen.generate(ast);
}
