#include "../include/ir.hpp"
#include "../include/ast.hpp"
#include <sstream>
#include <map>
#include <string>
#include <memory>

using namespace AC_IR;

// ═══════════════════════════════════════════════════════════════════════════
// BACKEND LOWERING STRATEGY (Pluggable)
// ═══════════════════════════════════════════════════════════════════════════
// Each backend implements this interface to define how IR maps to target code.
// Branch ONCE on backend type, then use polymorphism for everything else.
// ═══════════════════════════════════════════════════════════════════════════

class BackendStrategy {
public:
    virtual ~BackendStrategy() = default;
    
    // Emit helpers
    virtual void emit(std::ostringstream& out, int indent, const std::string& line) = 0;
    virtual void emitRaw(std::ostringstream& out, const std::string& line) = 0;
    
    // Header/imports
    virtual void emitHeader(std::ostringstream& out) = 0;
    
    // Reference formatting
    virtual std::string formatRef(const IRRef& r, SymbolTable* symbols) = 0;
    
    // Instructions
    virtual void emitStoreVar(std::ostringstream& out, int& indent, const std::string& var, const std::string& val) = 0;
    virtual void emitBinaryOp(std::ostringstream& out, int& indent, const std::string& result, const std::string& left, const std::string& right, char op) = 0;
    virtual void emitComparison(std::ostringstream& out, int& indent, const std::string& result, const std::string& left, const std::string& right, const std::string& op) = 0;
    virtual void emitCall(std::ostringstream& out, int& indent, const std::string& result, const std::string& func, const std::string& args) = 0;
    virtual void emitReturn(std::ostringstream& out, int& indent, const std::string& val) = 0;
    virtual void emitPrint(std::ostringstream& out, int& indent, const std::string& val) = 0;
    virtual void emitHalt(std::ostringstream& out, int& indent) = 0;
    
    // Control flow (HIR)
    virtual void emitIfBegin(std::ostringstream& out, int& indent, const std::string& cond) = 0;
    virtual void emitIfElse(std::ostringstream& out, int& indent) = 0;
    virtual void emitIfEnd(std::ostringstream& out, int& indent) = 0;
    
    // Control flow (LIR - for low-level backends)
    virtual void emitLabel(std::ostringstream& out, int indent, const std::string& label) = 0;
    virtual void emitJump(std::ostringstream& out, int indent, const std::string& label) = 0;
    virtual void emitJumpIfFalse(std::ostringstream& out, int indent, const std::string& cond, const std::string& label) = 0;
    
    // Functions
    virtual void emitFunctionBegin(std::ostringstream& out, int& indent, const std::string& name, const std::string& params) = 0;
    virtual void emitFunctionEnd(std::ostringstream& out, int& indent) = 0;
    
    // Main entry
    virtual void emitMainBegin(std::ostringstream& out, int& indent) = 0;
    virtual void emitMainEnd(std::ostringstream& out, int& indent) = 0;
};

// ═══════════════════════════════════════════════════════════════════════════
// PYTHON STRATEGY (HIR)
// ═══════════════════════════════════════════════════════════════════════════

class PythonStrategy : public BackendStrategy {
    void emit(std::ostringstream& out, int indent, const std::string& line) override {
        out << std::string(indent * 4, ' ') << line << "\n";
    }
    
    void emitRaw(std::ostringstream& out, const std::string& line) override {
        out << line << "\n";
    }
    
    void emitHeader(std::ostringstream& out) override {
        emitRaw(out, "# Generated by AC Compiler (AC->PY) from IR");
        emitRaw(out, "import sys");
        emitRaw(out, "");
    }
    
    std::string formatRef(const IRRef& r, SymbolTable* symbols) override {
        if (r.kind == IRRef::Kind::VAR || r.kind == IRRef::Kind::FUNCTION) {
            return r.toStringWithSymbols(symbols);
        }
        if (r.kind == IRRef::Kind::TEMP) return "t" + std::to_string(r.id);
        if (r.kind == IRRef::Kind::LABEL) return "L" + std::to_string(r.id);
        if (r.kind == IRRef::Kind::CONST) {
            if (r.value.type == IRType::INT) return std::to_string(std::get<int>(r.value.data));
            if (r.value.type == IRType::STRING) {
                std::string str = std::get<std::string>(r.value.data);
                if (str.size() >= 2 && str.front() == '$' && str.back() == '$') {
                    str = str.substr(1, str.size() - 2);
                }
                return "\"" + str + "\"";
            }
            if (r.value.type == IRType::BOOL) return std::get<bool>(r.value.data) ? "True" : "False";
        }
        return "0";
    }
    
    void emitStoreVar(std::ostringstream& out, int& indent, const std::string& var, const std::string& val) override {
        emit(out, indent, var + " = " + val);
    }
    
    void emitBinaryOp(std::ostringstream& out, int& indent, const std::string& result, const std::string& left, const std::string& right, char op) override {
        emit(out, indent, result + " = " + left + " " + op + " " + right);
    }
    
    void emitComparison(std::ostringstream& out, int& indent, const std::string& result, const std::string& left, const std::string& right, const std::string& op) override {
        emit(out, indent, result + " = " + left + " " + op + " " + right);
    }
    
    void emitCall(std::ostringstream& out, int& indent, const std::string& result, const std::string& func, const std::string& args) override {
        emit(out, indent, result + " = " + func + "(" + args + ")");
    }
    
    void emitReturn(std::ostringstream& out, int& indent, const std::string& val) override {
        emit(out, indent, val.empty() ? "return" : "return " + val);
    }
    
    void emitPrint(std::ostringstream& out, int& indent, const std::string& val) override {
        emit(out, indent, "print(" + val + ")");
    }
    
    void emitHalt(std::ostringstream& out, int& indent) override {
        emit(out, indent, "sys.exit(0)");
    }
    
    void emitIfBegin(std::ostringstream& out, int& indent, const std::string& cond) override {
        emit(out, indent, "if " + cond + ":");
        indent++;
    }
    
    void emitIfElse(std::ostringstream& out, int& indent) override {
        indent--;
        emit(out, indent, "else:");
        indent++;
    }
    
    void emitIfEnd(std::ostringstream& out, int& indent) override {
        indent--;
    }
    
    void emitLabel(std::ostringstream& out, int indent, const std::string& label) override {
        emit(out, indent, "# " + label + ":");
    }
    
    void emitJump(std::ostringstream& out, int indent, const std::string& label) override {
        emit(out, indent, "# goto " + label);
    }
    
    void emitJumpIfFalse(std::ostringstream& out, int indent, const std::string& cond, const std::string& label) override {
        emit(out, indent, "if not " + cond + ": # goto " + label);
    }
    
    void emitFunctionBegin(std::ostringstream& out, int& indent, const std::string& name, const std::string& params) override {
        emit(out, indent, "def " + name + "(" + params + "):");
        indent++;
    }
    
    void emitFunctionEnd(std::ostringstream& out, int& indent) override {
        indent--;
        emitRaw(out, "");
    }
    
    void emitMainBegin(std::ostringstream& out, int& indent) override {
        emit(out, indent, "if __name__ == \"__main__\":");
        indent++;
    }
    
    void emitMainEnd(std::ostringstream& out, int& indent) override {
        indent--;
    }
};

// ═══════════════════════════════════════════════════════════════════════════
// UNIFIED IR CODE GENERATOR (Strategy-based)
// ═══════════════════════════════════════════════════════════════════════════

class UnifiedIRCodeGen {
    const IRProgram& ir;
    std::unique_ptr<BackendStrategy> strategy;
    std::ostringstream out;
    int indentLevel = 0;
    
    std::string ref(const IRRef& r) {
        return strategy->formatRef(r, const_cast<SymbolTable*>(&ir.symbols));
    }
    
    void genInstr(const IRInstruction& i) {
        switch (i.opcode) {
            case IROpcode::LABEL:
                strategy->emitLabel(out, indentLevel, ref(i.typedOperands[0]));
                break;
                
            case IROpcode::STORE_VAR:
                strategy->emitStoreVar(out, indentLevel, ref(i.typedOperands[0]), ref(i.typedOperands[1]));
                break;
            
            case IROpcode::ADD:
            case IROpcode::SUB:
            case IROpcode::MUL:
            case IROpcode::DIV:
            case IROpcode::MOD: {
                char op = (i.opcode == IROpcode::ADD) ? '+' :
                         (i.opcode == IROpcode::SUB) ? '-' :
                         (i.opcode == IROpcode::MUL) ? '*' :
                         (i.opcode == IROpcode::DIV) ? '/' : '%';
                strategy->emitBinaryOp(out, indentLevel, ref(i.result), ref(i.typedOperands[0]), ref(i.typedOperands[1]), op);
                break;
            }
            
            case IROpcode::EQ:
            case IROpcode::NEQ:
            case IROpcode::LT:
            case IROpcode::GT:
            case IROpcode::LTE:
            case IROpcode::GTE: {
                std::string op = (i.opcode == IROpcode::EQ) ? "==" :
                                (i.opcode == IROpcode::NEQ) ? "!=" :
                                (i.opcode == IROpcode::LT) ? "<" :
                                (i.opcode == IROpcode::GT) ? ">" :
                                (i.opcode == IROpcode::LTE) ? "<=" : ">=";
                strategy->emitComparison(out, indentLevel, ref(i.result), ref(i.typedOperands[0]), ref(i.typedOperands[1]), op);
                break;
            }
            
            case IROpcode::JUMP:
                strategy->emitJump(out, indentLevel, ref(i.typedOperands[0]));
                break;
                
            case IROpcode::JUMP_IF_FALSE:
                strategy->emitJumpIfFalse(out, indentLevel, ref(i.typedOperands[0]), ref(i.typedOperands[1]));
                break;
            
            case IROpcode::CALL: {
                std::string func = ref(i.typedOperands[0]);
                std::string args;
                for (size_t j = 1; j < i.typedOperands.size(); j++) {
                    if (j > 1) args += ", ";
                    args += ref(i.typedOperands[j]);
                }
                strategy->emitCall(out, indentLevel, ref(i.result), func, args);
                break;
            }
            
            case IROpcode::RETURN:
                if (i.typedOperands.empty()) {
                    strategy->emitReturn(out, indentLevel, "");
                } else {
                    strategy->emitReturn(out, indentLevel, ref(i.typedOperands[0]));
                }
                break;
                
            case IROpcode::PRINT:
            case IROpcode::LIB_CALL: {
                if (!i.typedOperands.empty()) {
                    std::string method = ref(i.typedOperands[0]);
                    if (method == "Term.display" && i.typedOperands.size() > 1) {
                        strategy->emitPrint(out, indentLevel, ref(i.typedOperands[1]));
                    } else if (i.opcode == IROpcode::PRINT) {
                        strategy->emitPrint(out, indentLevel, ref(i.typedOperands[0]));
                    }
                }
                break;
            }
            
            case IROpcode::HALT:
                strategy->emitHalt(out, indentLevel);
                break;
                
            case IROpcode::IF_BEGIN:
                strategy->emitIfBegin(out, indentLevel, ref(i.typedOperands[0]));
                break;
                
            case IROpcode::IF_ELSE:
                strategy->emitIfElse(out, indentLevel);
                break;
                
            case IROpcode::IF_END:
                strategy->emitIfEnd(out, indentLevel);
                break;
                
            case IROpcode::FUNC_BEGIN:
            case IROpcode::FUNC_END:
            case IROpcode::NOP:
                // Metadata opcodes - no code generation
                break;
                
            default:
                break;
        }
    }
    
    void genFunction(const IRFunction& func) {
        std::string params;
        for (size_t i = 0; i < func.parameters.size(); i++) {
            if (i > 0) params += ", ";
            params += func.parameters[i];
        }
        
        strategy->emitFunctionBegin(out, indentLevel, func.name, params);
        
        for (const auto& instr : func.instructions) {
            genInstr(instr);
        }
        
        strategy->emitFunctionEnd(out, indentLevel);
    }
    
public:
    UnifiedIRCodeGen(const IRProgram& program) : ir(program) {
        // Branch ONCE on backend type to select strategy
        if (program.backend == "PY") {
            strategy = std::make_unique<PythonStrategy>();
        } else {
            // Fallback to Python for now (other strategies to be added)
            strategy = std::make_unique<PythonStrategy>();
        }
    }
    
    std::string generate() {
        strategy->emitHeader(out);
        
        // Generate functions
        for (const auto& func : ir.functions) {
            genFunction(func);
        }
        
        // Generate main entry point
        strategy->emitMainBegin(out, indentLevel);
        for (const auto& instr : ir.globalInit) {
            genInstr(instr);
        }
        strategy->emitMainEnd(out, indentLevel);
        
        return out.str();
    }
};

// Public API
std::string generateFromIR(const IRProgram& ir) {
    UnifiedIRCodeGen gen(ir);
    return gen.generate();
}
