# Generated by AC Compiler (AC->PY)
import sys

if __name__ == "__main__":
    x = 100
    # <mainloop>
    # <free>
    shared = 42
    # <free>
    if True:  # <bound>
        local_val = 99
        print(local_val)
    # <bound>
    print(x)
    print(shared)
    # <mainloop>
