# Generated by AC Compiler (AC->PY)
import sys

def main():
    while True:
        print("Before foreign code")
        # Preposterous: Foreign code is too Foreign (if this breaks, that's on you)
        import platform
        print("Foreign: running on", platform.system(), platform.release())
        print("After foreign code")
        sys.exit(0)

if __name__ == "__main__":
    main()
