// Generated by AC Compiler (AC->Go)
package main

import (
    "fmt"
    "os"
)

func main() {
    for {
        fmt.Println("Starting up...")
        result := 120
        fmt.Println(result)
        os.Exit(0)
    }
}
