// Generated by AC Compiler (AC->JS)
"use strict";

function main() {
    while (true) {
        function factorial(n) {
            if (n === 0) {
                return 1;
            } else if (n === 1) {
                return 1;
            } else {
                return n*(factorial(n-1));
            }
        }
        while (true) {
            let fruits = ["apple", "banana", "cherry"];
            for (const fruit of fruits) {
                console.log(fruit);
            }
            let result = factorial(5);
            console.log(result);
            if (typeof process !== 'undefined') process.exit(0); else throw new Error('__ac_exit__');
        }
    }
}

main();
