// Generated by AC Compiler (AC->V)
import os

fn factorial(n int) int {
    if n == 0 {
        return 1
    } else if n == 1 {
        return 1
    } else {
        return n*(factorial(n-1))
    }
}

fn main() {
    for {
        println('Starting up...')
        mut result := int(factorial(5))
        println(result)
        exit(0)
    }
}
