// Generated by AC Compiler (AC->C)
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int factorial(int arg) {
    if (arg == 0) {
        return 1;
    }
    else if (arg == 1) {
        return 1;
    }
    else {
        return arg*(factorial(arg-1));
    }
}


int main() {
    while (1) {
        printf("%s\n", "Starting up...");
        char* list[] = {"apple", "banana", "cherry"};
        for (int i = 0; i < 3; i++) {
            char* item = list[i];
            printf("%s\n", item);
        }
        int result = factorial(5);
        printf("%d\n", result);
        exit(0);
    }
return 0;
}
