// Generated by AC Compiler (AC->JS)
"use strict";


(function main() {
    while (true) {
        function factorial(n) {
            if (n = 0) {
                return 1;
            }
        }
        while (true) {
            let fruits = ["apple", "banana", "cherry"];
            for (let i = 0; i < fruits.length; ++i) {
                let fruit = fruits[i];
                console.log(fruit);
            }
            let result = factorial(5);
            console.log(result);
            if (typeof process !== 'undefined') process.exit(0); else throw new Error('__ac_exit__');
        }
    }
})();
