// Generated by AC Compiler (AC->Go)
package main

import (
    "fmt"
    "os"
)

// Event listener implementation
type EventListener struct {
    bindings map[string]func()
}
func NewEventListener() *EventListener {
    return &EventListener{bindings: make(map[string]func())}
}
func (el *EventListener) Bind(key string, callback func()) {
    el.bindings[key] = callback
}
func (el *EventListener) Trigger(key string) {
    // Automatically trigger if binding exists, otherwise do nothing
    if cb, ok := el.bindings[key]; ok { cb() }
}
func (el *EventListener) CheckAndTrigger(key string) {
    // Check and trigger - if no binding, do absolutely nothing
    el.Trigger(key)
}
var acEventListener = NewEventListener()

// Keybinds
const (
    KEY_1 = "1"
    KEY_2 = "2"
    KEY_3 = "3"
    KEY_4 = "4"
    KEY_5 = "5"
    KEY_6 = "6"
    KEY_7 = "7"
    KEY_8 = "8"
    KEY_9 = "9"
    KEY_0 = "0"
    KEY_MINUS = "minus"
    KEY_EQUAL = "equal"
    KEY_BACKSPACE = "backspace"
    KEY_BACKSLASH = "backslash"
    KEY_TAB = "tab"
    KEY_Q = "q"
    KEY_W = "w"
    KEY_E = "e"
    KEY_R = "r"
    KEY_T = "t"
    KEY_Y = "y"
    KEY_U = "u"
    KEY_I = "i"
    KEY_O = "o"
    KEY_P = "p"
    KEY_LBRACKET = "["
    KEY_RBRACKET = "]"
    KEY_CAPS = "caps"
    KEY_A = "a"
    KEY_S = "s"
    KEY_D = "d"
    KEY_F = "f"
    KEY_G = "g"
    KEY_H = "h"
    KEY_J = "j"
    KEY_K = "k"
    KEY_L = "l"
    KEY_SEMICOLON = ";"
    KEY_APOSTROPHE = "'"
    KEY_ENTER = "enter"
    KEY_SHIFT = "shift"
    KEY_Z = "z"
    KEY_X = "x"
    KEY_C = "c"
    KEY_V = "v"
    KEY_B = "b"
    KEY_N = "n"
    KEY_M = "m"
    KEY_COMMA = ","
    KEY_PERIOD = "."
    KEY_SLASH = "/"
    KEY_CTRL = "ctrl"
    KEY_ALT = "alt"
    KEY_SPACE = "space"
    KEY_FN = "fn"
    KEY_SUPER = "super"
    KEY_WINDOWS = "windows"
    KEY_UP = "up"
    KEY_DOWN = "down"
    KEY_LEFT = "left"
    KEY_RIGHT = "right"
)



func main() {
    for {
        fmt.Println("Starting up...")
        fmt.Println(result)
        os.Exit(0)
    }
}
