// Generated by AC Compiler (AC->Go)
package main

import (
    "fmt"
    "os"
)


func factorial(n int) int {
    if n == 0 {
        return 1
    }
    result := 1 // Numeral(Pos.Int)
    i := 1 // Numeral(Pos.Int)
    for i != n + 1 {
        result *= i
        i += 1
    }
    return result
}

func main() {
    for {
        fmt.Println("Starting up...")
        result := factorial(20) // Numeral(Pos.Int)
        fmt.Println(result)
        os.Exit(0)
    }
}
