// Generated by AC Compiler (AC->Rust)
use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

// Event listener implementation
struct EventListener {
    bindings: HashMap<String, Box<dyn Fn() + Send>>,
}
impl EventListener {
    fn new() -> Self { EventListener { bindings: HashMap::new() } }
    fn bind(&mut self, key: &str, callback: Box<dyn Fn() + Send>) {
        self.bindings.insert(key.to_string(), callback);
    }
    fn trigger(&self, key: &str) {
        // Automatically trigger if binding exists, otherwise do nothing
        if let Some(cb) = self.bindings.get(key) { cb(); }
    }
    fn check_and_trigger(&self, key: &str) {
        // Check and trigger - if no binding, do absolutely nothing
        self.trigger(key);
    }
}
static AC_EVENT_LISTENER: OnceLock<Mutex<EventListener>> = OnceLock::new();
fn get_event_listener() -> &'static Mutex<EventListener> {
    AC_EVENT_LISTENER.get_or_init(|| Mutex::new(EventListener::new()))
}

// Keybinds
const KEY_1: &str = "1";
const KEY_2: &str = "2";
const KEY_3: &str = "3";
const KEY_4: &str = "4";
const KEY_5: &str = "5";
const KEY_6: &str = "6";
const KEY_7: &str = "7";
const KEY_8: &str = "8";
const KEY_9: &str = "9";
const KEY_0: &str = "0";
const KEY_MINUS: &str = "minus";
const KEY_EQUAL: &str = "equal";
const KEY_BACKSPACE: &str = "backspace";
const KEY_BACKSLASH: &str = "backslash";
const KEY_TAB: &str = "tab";
const KEY_Q: &str = "q";
const KEY_W: &str = "w";
const KEY_E: &str = "e";
const KEY_R: &str = "r";
const KEY_T: &str = "t";
const KEY_Y: &str = "y";
const KEY_U: &str = "u";
const KEY_I: &str = "i";
const KEY_O: &str = "o";
const KEY_P: &str = "p";
const KEY_LBRACKET: &str = "[";
const KEY_RBRACKET: &str = "]";
const KEY_CAPS: &str = "caps";
const KEY_A: &str = "a";
const KEY_S: &str = "s";
const KEY_D: &str = "d";
const KEY_F: &str = "f";
const KEY_G: &str = "g";
const KEY_H: &str = "h";
const KEY_J: &str = "j";
const KEY_K: &str = "k";
const KEY_L: &str = "l";
const KEY_SEMICOLON: &str = ";";
const KEY_APOSTROPHE: &str = "'";
const KEY_ENTER: &str = "enter";
const KEY_SHIFT: &str = "shift";
const KEY_Z: &str = "z";
const KEY_X: &str = "x";
const KEY_C: &str = "c";
const KEY_V: &str = "v";
const KEY_B: &str = "b";
const KEY_N: &str = "n";
const KEY_M: &str = "m";
const KEY_COMMA: &str = ",";
const KEY_PERIOD: &str = ".";
const KEY_SLASH: &str = "/";
const KEY_CTRL: &str = "ctrl";
const KEY_ALT: &str = "alt";
const KEY_SPACE: &str = "space";
const KEY_FN: &str = "fn";
const KEY_SUPER: &str = "super";
const KEY_WINDOWS: &str = "windows";
const KEY_UP: &str = "up";
const KEY_DOWN: &str = "down";
const KEY_LEFT: &str = "left";
const KEY_RIGHT: &str = "right";



fn main() {
    loop {
        println!("{}", "Starting up...");
        println!("{}", result);
        std::process::exit(0);
    }
}
