// Generated by AC Compiler (AC->CPP)
#include <iostream>
#include <string>
#include <cstdlib>
using namespace std;

int main() {
    auto t0 = 5();
    auto x = t0;
    auto t1 = hello();
    auto name = t1;
    auto t2 = (long long)((!!(()!=0)) ^ (!!((is)!=0)));
    auto  = t2;
    auto t3 = (long long)((!!(()!=0)) ^ (!!((is)!=0)));
     = t3;
    auto 0 = raise("");
    return 0;
}
