# Generated by AC Compiler (AC->PY)
import sys

if __name__ == "__main__":
    t0 = 2 + 3
    x = t0
    y = 5
    t1 = 3 * 4
    z = t1
    w = 102
    t2 = 3 * 4
    t3 = 2 + t2
    result1 = t3
    t4 = ("2+3")
    t5 = t4 * 4
    result2 = t5
    a = 5>3
    b = 10<20
    c = 5is5
    neg = -5
    notval = notTrue
    t6 = 3 * 4
    t7 = 2 + t6
    t8 = t7 - 52
    complex = t8
