// Generated by AC Compiler (AC->C++)
#include <iostream>
#include <vector>
#include <string>
#include <map>
#include <functional>
#include <unordered_map>
using namespace std;




int main() {
    while (true) {
        logic.pushScope(/*args*/)
    }
return 0;
}
