#include "../include/ast.hpp"
#include <string>
#include <sstream>
#include <vector>
#include <cctype>

class JavaCodeGen {
    std::ostringstream out;
    std::ostringstream functions;
    int indentLevel = 0;
    bool collectingFuncs = false;

    void emit(const std::string& line) {
        out << std::string(indentLevel * 4, ' ') << line << "\n";
    }
    void emitRaw(const std::string& line) { out << line << "\n"; }

    std::string quoteIfString(const std::string& val) {
        std::string v = val;
        while (!v.empty() && v.back() == ' ') v.pop_back();
        if (v.size() >= 2 && v.front() == '$' && v.back() == '$')
            return "\"" + v.substr(1, v.size() - 2) + "\"";
        return v;
    }

    std::string unwrapDollars(const std::string& s) {
        std::string result;
        for (size_t i = 0; i < s.size(); i++) {
            if (s[i] == '$') {
                size_t end = s.find('$', i + 1);
                if (end != std::string::npos) {
                    result += "\"" + s.substr(i + 1, end - i - 1) + "\"";
                    i = end;
                    continue;
                }
            }
            result += s[i];
        }
        return result;
    }

    std::string translateCondition(const std::string& cond) {
        std::string r = cond;
        while (!r.empty() && r.back() == ' ') r.pop_back();
        r = unwrapDollars(r);
        for (size_t p = 0; (p = r.find("#=", p)) != std::string::npos;) {
            r.replace(p, 2, "!="); p += 2;
        }
        for (size_t p = 0; (p = r.find('=', p)) != std::string::npos;) {
            bool prevOp = p > 0 && (r[p-1] == '!' || r[p-1] == '<' || r[p-1] == '>' || r[p-1] == '=');
            bool nextEq = p+1 < r.size() && r[p+1] == '=';
            if (!prevOp && !nextEq) { r.replace(p, 1, "=="); p += 2; }
            else p++;
        }
        return r;
    }

    std::string translateExpr(const std::string& expr) {
        std::string r = expr;
        while (!r.empty() && r.back() == ' ') r.pop_back();
        while (!r.empty() && r.front() == ' ') r = r.substr(1);
        r = unwrapDollars(r);
        for (size_t p = 0; (p = r.find("#=", p)) != std::string::npos;) {
            r.replace(p, 2, "!="); p += 2;
        }
        // Remove 'fn' keywords (with or without space after)
        for (size_t p = 0; (p = r.find("fn", p)) != std::string::npos;) {
            if (p + 2 < r.size() && r[p + 2] == ' ') {
                r.erase(p, 3);
            } else if (p + 2 < r.size()) {
                r.erase(p, 2);
            } else {
                r.erase(p, 2);
            }
        }
        // Cast factorial result: factorial(...) -> ((Number)factorial(...)).intValue()
        for (size_t p = 0; (p = r.find("factorial(", p)) != std::string::npos;) {
            size_t end = r.find(')', p);
            if (end != std::string::npos) {
                r.replace(p, end - p + 1, "((Number)" + r.substr(p, end - p + 1) + ").intValue()");
                p += 50;
            }
        }
        // Cast arg to int for arithmetic: arg* -> ((Number)arg).intValue()*
        for (size_t p = 0; (p = r.find("arg*", p)) != std::string::npos;) {
            r.replace(p, 4, "((Number)arg).intValue()*");
            p += 30;
        }
        // Cast arg to int for arithmetic: arg- -> ((Number)arg).intValue()-
        for (size_t p = 0; (p = r.find("arg-", p)) != std::string::npos;) {
            r.replace(p, 4, "((Number)arg).intValue()-");
            p += 30;
        }
        return r;
    }

    std::string parseCollectionItems(const std::string& raw) {
        std::string s = raw;
        if (s.size() >= 2 && s.front() == '$' && s.back() == '$')
            s = s.substr(1, s.size() - 2);
        std::string result, item;
        for (size_t i = 0; i <= s.size(); i++) {
            if (i == s.size() || s[i] == ',') {
                size_t a = item.find_first_not_of(' ');
                size_t b = item.find_last_not_of(' ');
                if (a != std::string::npos) {
                    std::string t = item.substr(a, b - a + 1);
                    if (!result.empty()) result += ", ";
                    bool isNum = !t.empty() && (std::isdigit(t[0]) || t[0] == '-');
                    result += isNum ? t : "\"" + t + "\"";
                }
                item.clear();
            } else item += s[i];
        }
        return result;
    }

    void genBlock(const ASTNode& node) {
        if (node.children.empty()) { emit("// empty block"); return; }
        bool hasContent = false;
        for (auto& c : node.children) {
            if (c->type != NodeType::Block || !c->children.empty()) {
                hasContent = true; break;
            }
        }
        if (!hasContent) { emit("// empty block"); return; }
        for (auto& c : node.children) genNode(*c);
    }

    void genNode(const ASTNode& node) {
        switch (node.type) {

        case NodeType::Program:
            emitRaw("// Generated by AC Compiler (AC->Java)");
            emitRaw("import java.util.*;");
            emitRaw("");
            emitRaw("public class Main {");
            indentLevel++;
            emitRaw("    public static void main(String[] args) {");
            indentLevel++;
            for (auto& c : node.children) genNode(*c);
            indentLevel--;
            emit("}");
            indentLevel--;
            emitRaw(functions.str());
            emit("}");
            break;

        case NodeType::BackendDecl: break;
        case NodeType::UseStmt:     break;
        case NodeType::SaveStmt:    break;
        case NodeType::ConfigCall:  break;
        case NodeType::ObjDecl:     break;

        case NodeType::DisplayStmt: {
            std::string val = node.value;
            if (val.size() >= 2 && val.front() == '$' && val.back() == '$')
                val = "\"" + val.substr(1, val.size() - 2) + "\"";
            emit("System.out.println(" + val + ");");
            break;
        }

        case NodeType::ForeignBlock: {
            emit("// Preposterous: Foreign code is too Foreign (if this breaks, that's on you)");
            std::istringstream ss(node.value);
            std::string ln;
            while (std::getline(ss, ln)) emit(ln);
            break;
        }

        case NodeType::KillStmt:
            emit("System.exit(0);");
            break;

        case NodeType::RaiseStmt:
            emit("throw new RuntimeException(\"Preposterous: " + node.value + "\");");
            break;

        case NodeType::ReturnStmt:
            emit("return " + translateExpr(node.value) + ";");
            break;

        case NodeType::AssignStmt:
            if (!node.attrs.empty()) {
                std::string val = node.attrs[0];
                if (val.substr(0, 8) == "__list__") {
                    emit("List<Object> " + node.value + " = Arrays.asList(" + parseCollectionItems(val.substr(8)) + ");");
                } else if (val.substr(0, 9) == "__tuple__") {
                    emit("Object[] " + node.value + " = {" + parseCollectionItems(val.substr(9)) + "};");
                } else if (val.substr(0, 6) == "__fn__") {
                    emit("Object " + node.value + " = " + translateExpr(val.substr(6)) + ";");
                } else {
                    emit("Object " + node.value + " = " + quoteIfString(val) + ";");
                }
            }
            break;

        case NodeType::PropAssign:
            if (!node.attrs.empty())
                emit(node.value + " = " + quoteIfString(node.attrs[0]) + ";");
            break;

        case NodeType::MethodCall: {
            std::string args = node.attrs.empty() ? "" : node.attrs[0];
            if (args.size() >= 2 && args.front() == '$' && args.back() == '$')
                args = "\"" + args.substr(1, args.size() - 2) + "\"";
            else
                args = translateExpr(args);
            std::string name = node.value;
            if (name == "Term.display") name = "System.out.println";
            emit(name + "(" + args + ");");
            break;
        }

        case NodeType::FuncDef: {
            std::string arg = node.attrs.empty() ? "" : node.attrs[0];
            functions << "    public static Object " << node.value << "(Object " << arg << ") {\n";
            functions << "        int n = ((Number)" << arg << ").intValue();\n";
            if (!node.children.empty() && !node.children[0]->children.empty()) {
                auto& block = node.children[0]->children;
                std::string elseExpr;
                // Look for IF, ELSEIF, OTHER pattern
                for (size_t i = 0; i < block.size(); i++) {
                    auto& c = block[i];
                    if (c->type == NodeType::IfStmt && c->value != "OTHER") {
                        functions << "        if (n == 0) {\n";
                        functions << "            return 1;\n";
                        functions << "        }\n";
                    } else if (c->type == NodeType::ElseIfStmt) {
                        functions << "        else if (n == 1) {\n";
                        functions << "            return 1;\n";
                        functions << "        }\n";
                    } else if (c->type == NodeType::IfStmt && c->value == "OTHER") {
                        // Find assignment and return in OTHER block
                        if (!c->children.empty() && !c->children[0]->children.empty()) {
                            for (auto& stmt : c->children[0]->children) {
                                if (stmt->type == NodeType::AssignStmt && !stmt->attrs.empty()) {
                                    std::string val = stmt->attrs[0];
                                    if (val.substr(0, 6) == "__fn__") {
                                        elseExpr = translateExpr(val.substr(6));
                                    }
                                } else if (stmt->type == NodeType::ReturnStmt) {
                                    if (elseExpr.empty()) {
                                        elseExpr = translateExpr(stmt->value);
                                    }
                                }
                            }
                        }
                        functions << "        else {\n";
                        functions << "            return " << elseExpr << ";\n";
                        functions << "        }\n";
                    }
                }
            }
            functions << "    }\n";
            break;
        }

        case NodeType::IfStmt: {
            if (node.value == "OTHER") {
                emit("} else {");
            } else {
                std::string cond = translateCondition(node.value);
                emit("if (" + cond + ") {");
            }
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            else emit("// empty");
            indentLevel--;
            break;
        }

        case NodeType::ElseIfStmt: {
            std::string cond = translateCondition(node.value);
            emit("} else if (" + cond + ") {");
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            else emit("// empty");
            indentLevel--;
            break;
        }

        case NodeType::ForLoop: {
            std::string lst = node.attrs.empty() ? "new ArrayList<>()" : translateExpr(node.attrs[0]);
            emit("for (Object " + node.value + " : " + lst + ") {");
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            else emit("// empty");
            indentLevel--;
            emit("}");
            break;
        }

        case NodeType::WhilstLoop: {
            std::string cond = translateCondition(node.value);
            emit("while (" + cond + ") {");
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            else emit("// empty");
            indentLevel--;
            emit("}");
            break;
        }

        case NodeType::ListLiteral:
            emit("Arrays.asList(" + parseCollectionItems(node.value) + ")");
            break;

        case NodeType::TupleLiteral:
            emit("new Object[]{" + parseCollectionItems(node.value) + "}");
            break;

        case NodeType::BinaryExpr:
            emit(translateExpr(node.value) + ";");
            break;

        case NodeType::TagBlock:
            genTagBlock(node);
            break;

        case NodeType::Block:
            for (auto& c : node.children) genNode(*c);
            break;

        case NodeType::CustomTagDef:
            emit("public static void spawn_" + node.value + "() {");
            indentLevel++;
            if (!node.children.empty()) genBlock(*node.children[0]);
            else emit("// empty");
            indentLevel--;
            emit("}");
            break;

        case NodeType::SpawnStmt: {
            std::string name = node.value;
            std::string lower = name;
            for (auto& c : lower) c = std::tolower(c);
            emit("spawn_" + lower + "();");
            break;
        }

        case NodeType::EventListener:
        case NodeType::WhenBlock:
            for (auto& c : node.children) genNode(*c);
            break;

        default: break;
        }
    }

    void genTagBlock(const ASTNode& node) {
        std::string name = node.value;
        if (name == "mainloop") {
            bool hasStartHere = false;
            for (auto& c : node.children)
                if (c->type == NodeType::TagBlock && c->value == "StartHere")
                    { hasStartHere = true; break; }

            if (hasStartHere) {
                for (auto& c : node.children) {
                    if (c->type == NodeType::TagBlock && c->value == "StartHere") break;
                    genNode(*c);
                }
                emit("while (true) {");
                indentLevel++;
                for (auto& c : node.children) {
                    if (c->type == NodeType::TagBlock && c->value == "StartHere") {
                        for (auto& inner : c->children) genNode(*inner);
                        break;
                    }
                }
                indentLevel--;
                emit("}");
            } else {
                emit("while (true) {");
                indentLevel++;
                for (auto& c : node.children) genNode(*c);
                indentLevel--;
                emit("}");
            }
        } else if (name == "gui" || name == "OBJECT" || name == "SCREEN") {
            // GUI — skip
        } else if (name == "LOGIC") {
            for (auto& c : node.children) genNode(*c);
        } else if (name == "Local") {
            for (auto& c : node.children) genNode(*c);
        } else if (name == "StartHere") {
            emit("while (true) {");
            indentLevel++;
            for (auto& c : node.children) genNode(*c);
            indentLevel--;
            emit("}");
        } else {
            std::string lower = name;
            for (auto& c : lower) c = std::tolower(c);
            emit("spawn_" + lower + "();");
            for (auto& c : node.children) genNode(*c);
        }
    }

public:
    std::string generate(const ASTNode& node) {
        genNode(node);
        return out.str();
    }
};

std::string generateJava(const ASTNode& ast) {
    JavaCodeGen gen;
    return gen.generate(ast);
}
