# Generated by AC Compiler (AC->PY)
import sys

def main():
    while True:
        print("Starting up...")
        def factorial(n):
            if n == 0:
                return 1
            elif n == 1:
                return 1
            else:
                return n*(factorial(n-1))
        while True:
            fruits = ["apple", "banana", "cherry"]
            for fruit in fruits:
                print(fruit)
            result = factorial(5)
            print(result)
            sys.exit(0)

if __name__ == "__main__":
    main()
