// GENERATED by wasm/build.js from the .wat sources in this directory — do not hand-edit.
// Re-run `node wasm/build.js` after changing any .wat file.
#pragma once

namespace AcWasm {

// short/mini (32/16-bit wraparound int) support for the JS/HTML backend.
inline const char* SHORT_MINI_B64 =
    "AGFzbQEAAAABBgFgAX8BfwMDAgAABxMCBndyYXAzMgAABndyYXAxNgABChECBAAgAAsKACAAQRB0QRB1Cw==";

// `atomic` var support for the JS/HTML backend (real i32.atomic.load/store on shared
// linear memory, one cell per atomic variable).
inline const char* ATOMICS_B64 =
    "AGFzbQEAAAABDAJgAX8Bf2ACf38BfwMDAgABBQQBAQEBBxkDBm1lbW9yeQIABGxvYWQAAAVzdG9yZQABChcCCAAgAP4QAgALDAAgACAB/hcCACABCw==";

} // namespace AcWasm
