# Generated by AC Compiler (AC->PY)
import sys

if __name__ == "__main__":
    _dc_students_0 = {"name": "Alex", "age": 16, "grade": 91, "house": "Red"}
    _dc_students_1 = {"name": "Sam", "age": 17, "grade": 88, "house": "Blue"}
    _dc_students_2 = {"name": "Jordan", "age": 15, "grade": 97, "house": "Red"}
    _dc_students_3 = {"name": "Taylor", "age": 16, "grade": 74, "house": "Green"}
    _dc_students_4 = {"name": "Morgan", "age": 17, "grade": 82, "house": "Blue"}
    students = [_dc_students_0, _dc_students_1, _dc_students_2, _dc_students_3, _dc_students_4]
    # <mainloop>
    print("Loaded students:")
    print(students)
    # <mainloop>
