// Generated by AC Compiler (AC->LIB)
// Compile: g++ -std=c++17 -shared -fPIC <file>.cpp -o <file>.so
#include <iostream>
#include <string>
#include <vector>
#include <map>
#include <functional>
#include <cstdio>
#include <cstdlib>
typedef long long ac_int;
typedef const char* ac_str;

#ifdef __cplusplus
extern "C" {
#endif
long long helper(long long n) {
    auto t_7 = n * 2;
    return t_7;
    return 0;
}

#ifdef __cplusplus
} // extern "C"
#endif
#ifdef __cplusplus
extern "C" {
#endif
void ac_lib_init() {
    auto x = ac_pow(2, 3);
    std::vector<long long> t_2 = {1,2,3};
    auto y = ac_length(t_2);
    long long z = (long long)(5);
    auto _ac_cond_9 = 5;
    auto t_4 = false;
    if (t_4) {
        std::string a = std::to_string("one");
    } else {
        auto t_5 = (long long)(_ac_cond_9 == 2);
        if (t_5) {
            a = "two";
        } else {
            auto t_6 = (long long)(_ac_cond_9 == 5);
            if (t_6) {
                a = "five";
            } else {
                a = "other";
            }
        }
    }
    std::cout << x << "\n";
    std::cout << y << "\n";
    std::cout << a << "\n";
    auto t_8 = 8;
    std::cout << t_8 << "\n";
}
#ifdef __cplusplus
} // extern "C"
#endif
