#!/usr/bin/env node
// Compiles the .wat sources in this directory to WASM bytes (via wabt, a build-time-only
// tool — nothing in the AC compiler or its generated output depends on Node/wabt at
// runtime) and writes:
//   - include/wasm_blobs.hpp   base64 blobs the JS/HTML backend's emitHeader() inlines
//   - ncpu_mem.b64             base64 blob pasted by hand into native-cpu_ffi.js
//     (that file is a static, hand-maintained FFI shim, not compiler-generated output,
//     so its blob isn't wired in automatically — re-run this and re-paste if ncpu_mem.wat
//     ever changes)
//
// Run after editing any .wat file: node wasm/build.js

const fs = require('fs');
const path = require('path');
const wabtInit = require('wabt');

const HERE = __dirname;
const OUT_HPP = path.join(HERE, '..', 'include', 'wasm_blobs.hpp');
const OUT_NCPU_B64 = path.join(HERE, 'ncpu_mem.b64');

function compile(wabt, watFile) {
  const src = fs.readFileSync(path.join(HERE, watFile), 'utf8');
  const features = { threads: true }; // needed for atomics.wat's shared memory + atomic ops
  const mod = wabt.parseWat(watFile, src, features);
  mod.resolveNames();
  mod.validate(features);
  const { buffer } = mod.toBinary({});
  return Buffer.from(buffer).toString('base64');
}

wabtInit().then((wabt) => {
  const shortMini = compile(wabt, 'short_mini.wat');
  const atomics = compile(wabt, 'atomics.wat');
  const ncpuMem = compile(wabt, 'ncpu_mem.wat');

  const hpp = `// GENERATED by wasm/build.js from the .wat sources in this directory — do not hand-edit.
// Re-run \`node wasm/build.js\` after changing any .wat file.
#pragma once

namespace AcWasm {

// short/mini (32/16-bit wraparound int) support for the JS/HTML backend.
inline const char* SHORT_MINI_B64 =
    "${shortMini}";

// \`atomic\` var support for the JS/HTML backend (real i32.atomic.load/store on shared
// linear memory, one cell per atomic variable).
inline const char* ATOMICS_B64 =
    "${atomics}";

} // namespace AcWasm
`;
  fs.writeFileSync(OUT_HPP, hpp);
  fs.writeFileSync(OUT_NCPU_B64, ncpuMem + '\n');
  console.log('Wrote', OUT_HPP);
  console.log('Wrote', OUT_NCPU_B64, '(paste into native-cpu_ffi.js by hand)');
});
