#include "sapl_lower.hpp"
#include <sstream>

namespace aca {

static std::string emitExpr(const Expr& e);

static std::string emitStream(const std::string& op, const std::vector<ExprPtr>& args) {
    // args: [src, opVar("+"/"*"), payload...]
    if (args.size() < 2) return "/* bad stream */";
    const Expr& src = *args[0];
    std::string reducer = op;
    if (reducer == "+") return "E " + emitExpr(src);
    if (reducer == "*") return "PI " + emitExpr(src);
    return "/* stream " + reducer + " */ " + emitExpr(src);
}

static std::string emitCall(const std::string& name, const std::vector<ExprPtr>& args) {
    // Minimal mappings for benchmark
    if (name == "Term.display" && args.size() == 1) return "0<- " + emitExpr(*args[0]);
    if (name == "count" && args.size() == 1) return "pw " + emitExpr(*args[0]);
    if (name == "__stream__" && args.size() >= 2) {
        const Expr& opExpr = *args[1];
        std::string op = "+";
        if (opExpr.kind == ExprKind::Var) op = std::get<std::string>(opExpr.data);
        return emitStream(op, args);
    }

    std::ostringstream ss;
    ss << name << "(";
    for (size_t i = 0; i < args.size(); i++) {
        if (i) ss << ", ";
        ss << emitExpr(*args[i]);
    }
    ss << ")";
    return ss.str();
}

static std::string emitExpr(const Expr& e) {
    switch (e.kind) {
        case ExprKind::Literal: {
            const auto& lit = std::get<LitValue>(e.data);
            if (std::holds_alternative<int64_t>(lit.v)) return std::to_string(std::get<int64_t>(lit.v));
            if (std::holds_alternative<DecMap>(lit.v)) {
                // SAPL currently reads numbers as double; emit as comment + best-effort decimal text.
                return "/* dec " + decMapToDebug(std::get<DecMap>(lit.v)) + " */ 0.0";
            }
            if (std::holds_alternative<std::string>(lit.v)) return "\"" + std::get<std::string>(lit.v) + "\"";
            if (std::holds_alternative<bool>(lit.v)) return (std::get<bool>(lit.v) ? "1" : "0");
            return "0";
        }
        case ExprKind::Var:
            return std::get<std::string>(e.data);
        case ExprKind::Binary: {
            const auto& t = std::get<std::tuple<std::string, ExprPtr, ExprPtr>>(e.data);
            const std::string& op = std::get<0>(t);
            return "(" + emitExpr(*std::get<1>(t)) + " " + op + " " + emitExpr(*std::get<2>(t)) + ")";
        }
        case ExprKind::Call: {
            const auto& t = std::get<std::tuple<std::string, std::vector<ExprPtr>>>(e.data);
            return emitCall(std::get<0>(t), std::get<1>(t));
        }
        case ExprKind::List: {
            const auto& items = std::get<std::vector<ExprPtr>>(e.data);
            std::ostringstream ss;
            ss << "[";
            for (size_t i = 0; i < items.size(); i++) {
                if (i) ss << " ";
                ss << emitExpr(*items[i]);
            }
            ss << "]";
            return ss.str();
        }
        case ExprKind::Range: {
            const auto& pr = std::get<std::pair<ExprPtr, ExprPtr>>(e.data);
            return "I " + emitExpr(*pr.first) + " " + emitExpr(*pr.second);
        }
    }
    return "0";
}

static void emitStmt(std::ostringstream& ss, const Stmt& s) {
    switch (s.kind) {
        case StmtKind::Assign: {
            const auto& a = std::get<AssignPayload>(s.data);
            if (a.op == "=") ss << a.name << " = " << emitExpr(*a.expr) << "\n";
            else ss << "/* " << a.name << " " << a.op << " ... */\n";
            return;
        }
        case StmtKind::ExprOnly: {
            const auto& e = std::get<ExprPtr>(s.data);
            ss << emitExpr(*e) << "\n";
            return;
        }
        case StmtKind::Return: {
            const auto& r = std::get<ReturnPayload>(s.data);
            ss << "return " << emitExpr(*r.expr) << "\n";
            return;
        }
        case StmtKind::If: {
            ss << "/* if-stmt not lowered yet */\n";
            return;
        }
    }
}

std::string lowerToSapl(const Program& prog) {
    std::ostringstream ss;
    ss << "; Generated by aca-compiler (AC*)\n";
    ss << "; Source header: " << (prog.header.empty() ? "<none>" : prog.header) << "\n\n";
    ss << "; NOTE: This SAPL output is a first-pass lowering scaffold.\n";
    ss << "; It is always emitted for caching, but not all AC* constructs are lowered yet.\n\n";

    ss << "; mainloop\n";
    for (auto& st : prog.mainloop) emitStmt(ss, *st);
    ss << "\n";
    return ss.str();
}

} // namespace aca

