/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include "library/ilib/widgets/widgets_c.h"
// Link: gcc output.c -L./library/ilib/widgets -lacwidgets
#include "library/ilib/os/os_c.h"
// Link: gcc output.c -L./library/ilib/os -lacos

typedef long long ac_int;
typedef const char* ac_str;

ac_int OnSubmit(void) {
    ac_int n = name_inp_get();
    ac_int e = email_inp_get();
    ac_int ph = phone_inp_get();
    ac_int pos = pos_drop_get();
    ac_int exp = exp_drop_get();
    ac_int t5 = "{\"name\":\"" + n;
    ac_int t6 = t5 + "\",\"email\":\"";
    ac_int t7 = t6 + e;
    ac_int t8 = t7 + "\",\"phone\":\"";
    ac_int t9 = t8 + ph;
    ac_int t10 = t9 + "\",\"position\":\"";
    ac_int t11 = t10 + pos;
    ac_int t12 = t11 + "\",\"experience\":\"";
    ac_int t13 = t12 + exp;
    ac_int entry = t13 + "\"}";
    os_append_to("applicants.ndjson", entry);
    status_lbl_set("Saved! Entry appended to applicants.ndjson");
}

int main()
{
    // <mainloop>
    ac_int root = Screen("Job Application Form", "500x560");
    ac_int _h = display(root, "=== Job Application Form ===");
    _h = display(root, "Full Name:");
    ac_int name_inp = ask(root, 45);
    _h = display(root, "Email Address:");
    ac_int email_inp = ask(root, 45);
    _h = display(root, "Phone Number:");
    ac_int phone_inp = ask(root, 45);
    _h = display(root, "Position Applied For:");
    ac_int pos_drop = dropdown(root, lazy);
    pos_drop_add("Software Engineer");
    pos_drop_add("Product Manager");
    pos_drop_add("UX Designer");
    pos_drop_add("Data Scientist");
    pos_drop_add("DevOps Engineer");
    pos_drop_add("QA Engineer");
    pos_drop_pack();
    _h = display(root, "Experience Level:");
    ac_int exp_drop = dropdown(root, lazy);
    exp_drop_add("Junior   (0-2 years)");
    exp_drop_add("Mid-Level (3-5 years)");
    exp_drop_add("Senior   (5+ years)");
    exp_drop_pack();
    ac_int status_lbl = display(root, "");
    _h = btn(root, "Submit Application", OnSubmit);
    root_mainloop();
    // <mainloop>
}
