/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include "library/ilib/machine-audio/machine-audio_c.h"
// Link: gcc output.c -L./library/ilib/machine-audio -lacmachinaaudio

typedef long long ac_int;
typedef const char* ac_str;

ac_int __ac_shutoff__(void) {
    maudio.stop();
}

int main()
{
    // <mainloop>
    printf("%s\n", "=== AC Machine Audio Test ====");
    ac_int tts_ready = maudio_tts_ok();
    ac_int t0 = (ac_int)(tts_ready == 1);
    if (t0) {
        printf("%s\n", "TTS available — speaking...");
        maudio_speak("Hello. I am AC. This is a text to speech test.");
        maudio_speak("The quick brown fox jumps over the lazy dog.");
    } else {
        printf("%s\n", "No TTS engine found.");
    }
    printf("%s\n", "Listening for 4 seconds — say something...");
    ac_int heard = maudio_listen(4000);
    ac_int t1 = (ac_int)(heard == "");
    if (t1) {
        printf("%s\n", "Nothing heard or STT unavailable.");
    } else {
        printf("%s\n", "You said:");
        printf("%lld\n", (long long)(heard));
    }
    ac_int t2 = (ac_int)(tts_ready == 1);
    if (t2) {
        maudio_speak("Test complete.");
    }
    printf("%s\n", "Done.");
    // <mainloop>
}
