/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include "library/ilib/math/math_c.h"
// Link: gcc output.c -L./library/ilib/math -lacmath

typedef long long ac_int;
typedef const char* ac_str;

int main()
{
    // <mainloop>
    printf("%s\n", "======================================");
    printf("%s\n", "       AC  Terminal  Calculator       ");
    printf("%s\n", "======================================");
    printf("%s\n", "  type help for commands, quit to exit");
    printf("%s\n", "======================================");
    double ans = (double)(0.0);
    double mem = (double)(0.0);
    double h1 = (double)(0.0);
    double h2 = (double)(0.0);
    double h3 = (double)(0.0);
    ac_int running = (ac_int)(1);
    while (1) {
        ac_int t0 = (ac_int)(running == 1);
        if (!(t0)) break;
        printf("%s", "> ");
        char _buf_line[4096];
        fgets(_buf_line, sizeof(_buf_line), stdin);
        _buf_line[strcspn(_buf_line, "\n")] = 0;
        ac_str line = _buf_line;
        ac_int t2 = (ac_int)(line == "quit");
        if (t2) {
            printf("%s\n", "Goodbye!");
            running = 0;
        } else {
            ac_int t3 = (ac_int)(line == "help");
            if (t3) {
                printf("%s\n", "");
                printf("%s\n", "  ARITHMETIC    + - * / @ (power)");
                printf("%s\n", "  TRIG          sin(x) cos(x) tan(x)");
                printf("%s\n", "  INVERSE TRIG  asin(x) acos(x) atan(x)");
                printf("%s\n", "  ROOTS         sqrt(x) cbrt(x) hypot(a,b)");
                printf("%s\n", "  LOGS          ln(x)  log(base,x)  log2(x)  log10(x)");
                printf("%s\n", "  ROUNDING      floor(x) ceil(x) round(x)");
                printf("%s\n", "  CONVERSION    deg2rad(x)  rad2deg(x)");
                printf("%s\n", "  CONSTANTS     pi  e  tau  em");
                printf("%s\n", "  RECALL        ans  h1  h2  h3");
                printf("%s\n", "  MEMORY        ms=store  mr=recall  mc=clear");
                printf("%s\n", "  COMMANDS      hist  consts  degrees  radians  quit");
                printf("%s\n", "");
            } else {
                ac_int t4 = (ac_int)(line == "hist");
                if (t4) {
                    printf("%s\n", "  --- History ---");
                    printf("%.16g\n", (double)(h1));
                    printf("%.16g\n", (double)(h2));
                    printf("%.16g\n", (double)(h3));
                } else {
                    ac_int t5 = (ac_int)(line == "consts");
                    if (t5) {
                        printf("%s\n", "  pi  (π)  =");
                        printf("%lld\n", (long long)(math_pi));
                        printf("%s\n", "  e        =");
                        printf("%lld\n", (long long)(math_e));
                        printf("%s\n", "  tau (τ)  =");
                        printf("%lld\n", (long long)(math_tau));
                        printf("%s\n", "  em  (γ)  =");
                        printf("%lld\n", (long long)(math_em));
                    } else {
                        ac_int t6 = (ac_int)(line == "degrees");
                        if (t6) {
                            ac_int result = math_rad2deg(ans);
                            printf("%lld\n", (long long)(result));
                        } else {
                            ac_int t8 = (ac_int)(line == "radians");
                            if (t8) {
                                result = math_deg2rad(ans);
                                printf("%lld\n", (long long)(result));
                            } else {
                                ac_int t10 = (ac_int)(line == "ms");
                                if (t10) {
                                    mem = ans;
                                    printf("%s\n", "  Stored:");
                                    printf("%.16g\n", (double)(mem));
                                } else {
                                    ac_int t11 = (ac_int)(line == "mr");
                                    if (t11) {
                                        printf("%s\n", "  Memory:");
                                        printf("%.16g\n", (double)(mem));
                                    } else {
                                        ac_int t12 = (ac_int)(line == "mc");
                                        if (t12) {
                                            mem = 0.0;
                                            printf("%s\n", "  Memory cleared");
                                        } else {
                                            result = ac_eval(line);
                                            h3 = h2;
                                            h2 = h1;
                                            h1 = result;
                                            ans = result;
                                            printf("%lld\n", (long long)(result));
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    _exit(1);
    // <mainloop>
}
