/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>

typedef long long ac_int;
typedef const char* ac_str;

ac_int fib(ac_int n) {
    ac_int t_0 = (ac_int)(n <= 1);
    if (t_0) {
        return n;
    } else {
        ac_int t_2 = n - 1;
        ac_int t_1 = fib(t_2);
        ac_int t_4 = n - 2;
        ac_int t_3 = fib(t_4);
        ac_int t_5 = t_1 + t_3;
        return t_5;
    }
}

int main()
{
    // <mainloop>
    ac_int i = (ac_int)(0);
    __typeof__(i) _ac_s0_i = i;
    while (1) {
        ac_int t_6 = (ac_int)(i <= 10);
        if (!(t_6)) break;
        ac_int t_7 = fib(i);
        printf("%lld\n", (long long)(t_7));
        i = i + 1;
    }
    i = _ac_s0_i;
    abort();
    // <mainloop>
}
