/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

typedef long long ac_int;
typedef const char* ac_str;

ac_int fib(ac_int n) {
    ac_int t0 = (ac_int)(n <= 1);
    if (!(t0)) goto L0;
    return n;
    goto L1;
L0:;
    ac_int t2 = n - 1;
    ac_int t1 = fib(t2);
    ac_int t4 = n - 2;
    ac_int t3 = fib(t4);
    ac_int t5 = t1 + t3;
    return t5;
L1:;
}

int main()
{
    ac_int i = 0;
L2:;
    ac_int t6 = (ac_int)(i <= 10);
    if (!(t6)) goto L3;
    ac_int t7 = fib(i);
    printf("%lld\n", (long long)(t7));
    i = i + 1;
    goto L2;
L3:;
    exit(0);
}
