/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include "library/ilib/gl/gl_c.h"
// Link: gcc output.c -L./library/ilib/gl -lacgl

typedef long long ac_int;
typedef const char* ac_str;

ac_str Character = "Character";
ac_str Cactus = "Cactus";

ac_int jump(ac_int arg) {
    double t0 = ac_gl_is_obj(arg);
    ac_int t1 = (ac_int)(!(t0));
    if (t1) {
        fprintf(stderr, "Preposterous: %s\n", "That is not a valid object"); exit(1);
    } else {
        ac_gl_obj_move_y(arg, -180.0);
        ac_gl_obj_vertex(arg, 400.0, 600.0);
        ac_gl_obj_curveshape(arg, "-x^2");
    }
}

ac_int spawn_terrain(void) {
    ac_gl_obj_create("Cactus");
    ac_gl_obj_config_item("Cactus", "geometry(100 width @ 300 height)");
    double t3 = ac_gl_hitbox_overlap("Character", "Cactus");
    if (t3) {
        ac_gl_obj_circle_fall("Cactus", 0.25, "right");
    }
    ac_gl_obj_animate("Cactus", "left", 300.0);
    double t4 = ac_gl_obj_circle_fell("Cactus", 0.25, "right");
    ac_int t6 = (ac_int)(t4 == 1);
    if (t6) {
        ac_gl_obj_regen("Cactus");
    }
}

ac_int __keycb_space(void) {
    jump(Character);
}

int main()
{
    // <mainloop>
    // <gui>
    // <OBJECT>
    ac_gl_obj_create("Character");
    ac_gl_obj_config_item("Character", "square(50)");
    ac_gl_obj_pos_from_spec("Character", "center", "screen-50");
    ac_gl_obj_color_by_name("Character", "white");
    ac_gl_obj_create("Cactus");
    ac_gl_obj_config_item("Cactus", "geometry(100 width @ 300 height)");
    ac_gl_obj_pos_from_spec("Cactus", "right", "screen-300");
    ac_gl_obj_color_by_name("Cactus", "brown");
    // <OBJECT>
    // <SCREEN>
    ac_gl_screen_init(1720, 1080, "Geodeo");
    ac_gl_screen_set_bg_by_name("green");
    ac_gl_screen_animate("60fps");
    // <SCREEN>
    // <LOGIC>
    // <StartHere>
    while (1) {
        double t7 = ac_gl_frame_begin();
        if (!(t7)) break;
        ac_int t8 = spawn_terrain();
        while (1) {
            double t9 = ac_gl_hitbox_many_overlap();
            if (!(t9)) break;
            jump(Character);
        }
        ac_gl_frame_render();
        ac_gl_frame_end();
    }
    // <StartHere>
    // <LOGIC>
    // <gui>
    // <mainloop>
}
