/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include "library/ilib/gl/gl_c.h"
// Link: gcc output.c -L./library/ilib/gl -lacgl

typedef long long ac_int;
typedef const char* ac_str;

ac_str Ball = "Ball";
ac_str Paddle = "Paddle";

ac_int reset_ball(ac_int arg) {
    double t0 = ac_gl_is_obj(arg);
    ac_int t1 = (ac_int)(!(t0));
    if (t1) {
        fprintf(stderr, "Preposterous: %s\n", "Not a valid object"); exit(1);
    } else {
        ac_gl_obj_regen(arg);
    }
}

ac_int __keycb_space(void) {
    reset_ball(Ball);
}

int main()
{
    // <mainloop>
    // <gui>
    // <OBJECT>
    ac_gl_obj_create("Ball");
    ac_gl_obj_config_item("Ball", "square(28)");
    ac_gl_obj_pos_from_spec("Ball", "center", "center");
    ac_gl_obj_color_by_name("Ball", "white");
    ac_gl_obj_create("Paddle");
    ac_gl_obj_config_item("Paddle", "geometry(180 width @ 16 height)");
    ac_gl_obj_pos_from_spec("Paddle", "center", "screen-50");
    ac_gl_obj_color_by_name("Paddle", "white");
    // <OBJECT>
    // <SCREEN>
    ac_gl_screen_init(1720, 1080, "Geodeo");
    ac_gl_screen_set_bg_by_name("black");
    ac_gl_screen_animate("60fps");
    // <SCREEN>
    // <LOGIC>
    // <StartHere>
    while (1) {
        double t2 = ac_gl_frame_begin();
        if (!(t2)) break;
        ac_gl_obj_animate("Ball", "right", 300.0);
        ac_gl_obj_circle_fall("Ball", 0.25, "right");
        double t3 = ac_gl_obj_circle_fell("Ball", 0.25, "right");
        ac_int t5 = (ac_int)(t3 == 1);
        if (t5) {
            ac_gl_obj_regen("Ball");
        }
        double t7 = ac_gl_hitbox_overlap("Ball", "Paddle");
        if (t7) {
            ac_gl_obj_circle_fall("Ball", 0.25, "right");
        }
        ac_gl_frame_render();
        ac_gl_frame_end();
    }
    // <StartHere>
    // <LOGIC>
    // <gui>
    // <mainloop>
}
