/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>

typedef long long ac_int;
typedef const char* ac_str;

int main()
{
    // <mainloop>
    printf("%s\n", "Hello, World!");
    abort();
    // <mainloop>
}
