/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include "library/ilib/machine-audio/machine-audio_c.h"
// Link: gcc output.c -L./library/ilib/machine-audio -lacmachinaaudio
#include "library/ilib/os/os_c.h"
// Link: gcc output.c -L./library/ilib/os -lacos

typedef long long ac_int;
typedef const char* ac_str;

ac_int resolve(ac_int s) {
    ac_int cmd = s;
    ac_int t0 = s_find("google");
    ac_int t1 = 0 - 1;
    ac_int t2 = (ac_int)(t0 > t1);
    if (t2) {
        cmd = "google-chrome";
    } else {
        ac_int t3 = s_find("chrome");
        ac_int t4 = 0 - 1;
        ac_int t5 = (ac_int)(t3 > t4);
        if (t5) {
            cmd = "google-chrome";
        } else {
            ac_int t6 = s_find("firefox");
            ac_int t7 = 0 - 1;
            ac_int t8 = (ac_int)(t6 > t7);
            if (t8) {
                cmd = "firefox";
            } else {
                ac_int t9 = s_find("mozilla");
                ac_int t10 = 0 - 1;
                ac_int t11 = (ac_int)(t9 > t10);
                if (t11) {
                    cmd = "firefox";
                } else {
                    ac_int t12 = s_find("nautilus");
                    ac_int t13 = 0 - 1;
                    ac_int t14 = (ac_int)(t12 > t13);
                    if (t14) {
                        cmd = "nautilus";
                    } else {
                        ac_int t15 = s_find("files");
                        ac_int t16 = 0 - 1;
                        ac_int t17 = (ac_int)(t15 > t16);
                        if (t17) {
                            cmd = "nautilus";
                        } else {
                            ac_int t18 = s_find("terminal");
                            ac_int t19 = 0 - 1;
                            ac_int t20 = (ac_int)(t18 > t19);
                            if (t20) {
                                cmd = "gnome-terminal";
                            } else {
                                ac_int t21 = s_find("console");
                                ac_int t22 = 0 - 1;
                                ac_int t23 = (ac_int)(t21 > t22);
                                if (t23) {
                                    cmd = "gnome-terminal";
                                } else {
                                    ac_int t24 = s_find("visual studio");
                                    ac_int t25 = 0 - 1;
                                    ac_int t26 = (ac_int)(t24 > t25);
                                    if (t26) {
                                        cmd = "code";
                                    } else {
                                        ac_int t27 = s_find("vscode");
                                        ac_int t28 = 0 - 1;
                                        ac_int t29 = (ac_int)(t27 > t28);
                                        if (t29) {
                                            cmd = "code";
                                        } else {
                                            ac_int t30 = s_find("code");
                                            ac_int t31 = 0 - 1;
                                            ac_int t32 = (ac_int)(t30 > t31);
                                            if (t32) {
                                                cmd = "code";
                                            } else {
                                                ac_int t33 = s_find("spotify");
                                                ac_int t34 = 0 - 1;
                                                ac_int t35 = (ac_int)(t33 > t34);
                                                if (t35) {
                                                    cmd = "spotify";
                                                } else {
                                                    ac_int t36 = s_find("discord");
                                                    ac_int t37 = 0 - 1;
                                                    ac_int t38 = (ac_int)(t36 > t37);
                                                    if (t38) {
                                                        cmd = "discord";
                                                    } else {
                                                        ac_int t39 = s_find("slack");
                                                        ac_int t40 = 0 - 1;
                                                        ac_int t41 = (ac_int)(t39 > t40);
                                                        if (t41) {
                                                            cmd = "slack";
                                                        } else {
                                                            ac_int t42 = s_find("vlc");
                                                            ac_int t43 = 0 - 1;
                                                            ac_int t44 = (ac_int)(t42 > t43);
                                                            if (t44) {
                                                                cmd = "vlc";
                                                            } else {
                                                                ac_int t45 = s_find("gimp");
                                                                ac_int t46 = 0 - 1;
                                                                ac_int t47 = (ac_int)(t45 > t46);
                                                                if (t47) {
                                                                    cmd = "gimp";
                                                                } else {
                                                                    ac_int t48 = s_find("steam");
                                                                    ac_int t49 = 0 - 1;
                                                                    ac_int t50 = (ac_int)(t48 > t49);
                                                                    if (t50) {
                                                                        cmd = "steam";
                                                                    } else {
                                                                        ac_int t51 = s_find("calculator");
                                                                        ac_int t52 = 0 - 1;
                                                                        ac_int t53 = (ac_int)(t51 > t52);
                                                                        if (t53) {
                                                                            cmd = "gnome-calculator";
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    return cmd;
}

ac_int __ac_shutoff__(void) {
    maudio.stop();
}

int main()
{
    // <mainloop>
    printf("%s\n", "=============================");
    printf("%s\n", "  JARVIS — App Launcher");
    printf("%s\n", "=============================");
    printf("%s\n", "Say an app name to open it.");
    printf("%s\n", "Ctrl+C to quit.");
    printf("%s\n", "");
    while (1) {
        if (!(1)) break;
        printf("%s\n", "Listening...");
        ac_int speech = maudio_listen(8000);
        ac_int t56 = (ac_int)(speech == "");
        if (t56) {
            continue;
        }
        ac_int low = speech_lower();
        ac_int cmd = resolve(low);
        printf("%lld\n", (long long)(cmd));
        ac_int rc = os_sbash(cmd);
        ac_int t59 = (ac_int)(rc < 0);
        if (t59) {
            printf("%s\n", "[BLOCKED] sbash refused that command.");
        }
        printf("%s\n", "");
    }
    // <mainloop>
}
