/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "library/math/math_c.h"
// Link: gcc output.c -L./library/math -lacmath

typedef long long ac_int;
typedef const char* ac_str;

int main()
{
    printf("%s\n", "--- Constants ---");
    printf("%.16g\n", (double)(math_pi));
    printf("%.16g\n", (double)(math_e));
    printf("%.16g\n", (double)(math_tau));
    printf("%.16g\n", (double)(math_em));
    printf("%s\n", "--- Pi / E with precision ---");
    double t0 = ac_math_pi(5);
    printf("%.16g\n", (double)(t0));
    double t1 = ac_math_e(4);
    printf("%.16g\n", (double)(t1));
    printf("%s\n", "--- Powers and Roots ---");
    double t2 = math_sqrt(16.0);
    printf("%.16g\n", (double)(t2));
    double t3 = math_cbrt(27.0);
    printf("%.16g\n", (double)(t3));
    double t4 = math_pow(2.0, 10.0);
    printf("%.16g\n", (double)(t4));
    double t5 = math_hypot(3.0, 4.0);
    printf("%.16g\n", (double)(t5));
    printf("%s\n", "--- Logarithms ---");
    double t6 = math_ln(math_e);
    printf("%.16g\n", (double)(t6));
    double t7 = math_log(10.0, 1000.0);
    printf("%.16g\n", (double)(t7));
    double t8 = math_log(2.0, 1024.0);
    printf("%.16g\n", (double)(t8));
    double t9 = math_log10(1000.0);
    printf("%.16g\n", (double)(t9));
    double t10 = math_log2(1024.0);
    printf("%.16g\n", (double)(t10));
    printf("%s\n", "--- Rounding ---");
    double t11 = math_floor(4.9);
    printf("%.16g\n", (double)(t11));
    double t12 = math_ceil(4.1);
    printf("%.16g\n", (double)(t12));
    double t13 = math_round(4.5);
    printf("%.16g\n", (double)(t13));
    double t15 = 0 - 7.3;
    double t14 = math_abs(t15);
    printf("%.16g\n", (double)(t14));
    printf("%s\n", "--- Clamp ---");
    double t16 = math_clamp(5.0, 0.0, 10.0);
    printf("%.16g\n", (double)(t16));
    double t18 = 0 - 3.0;
    double t17 = math_clamp(t18, 0.0, 10.0);
    printf("%.16g\n", (double)(t17));
    double t19 = math_clamp(15.0, 0.0, 10.0);
    printf("%.16g\n", (double)(t19));
    printf("%s\n", "--- Conversions ---");
    ac_int t20 = math_to_int(3.99);
    printf("%lld\n", (long long)(t20));
    double t21 = math_to_dec(42);
    printf("%.16g\n", (double)(t21));
    exit(0);
}
