/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include "/home/abu/Documents/kiro projects/AC/AC/library/ilib/math/math_c.h"
// Link: gcc output.c -L"/home/abu/Documents/kiro projects/AC/AC/library/ilib/math" -lacmath -Wl,-rpath,"/home/abu/Documents/kiro projects/AC/AC/library/ilib/math"

typedef long long ac_int;
typedef const char* ac_str;

int main()
{
    // <mainloop>
    printf("%s\n", "--- Constants ---");
    printf("%lld\n", (long long)(math_pi));
    printf("%lld\n", (long long)(math_e));
    printf("%lld\n", (long long)(math_tau));
    printf("%lld\n", (long long)(math_em));
    printf("%s\n", "--- Pi / E with precision ---");
    double t_0 = ac_math_pi(5);
    printf("%.16g\n", (double)(t_0));
    double t_1 = ac_math_e(4);
    printf("%.16g\n", (double)(t_1));
    printf("%s\n", "--- Powers and Roots ---");
    ac_int t_2 = math_sqrt(16.0);
    printf("%lld\n", (long long)(t_2));
    ac_int t_3 = math_cbrt(27.0);
    printf("%lld\n", (long long)(t_3));
    ac_int t_4 = math_pow(2.0, 10.0);
    printf("%lld\n", (long long)(t_4));
    ac_int t_5 = math_hypot(3.0, 4.0);
    printf("%lld\n", (long long)(t_5));
    printf("%s\n", "--- Logarithms ---");
    ac_int t_6 = math_ln(math_e);
    printf("%lld\n", (long long)(t_6));
    ac_int t_7 = math_log(10.0, 1000.0);
    printf("%lld\n", (long long)(t_7));
    ac_int t_8 = math_log(2.0, 1024.0);
    printf("%lld\n", (long long)(t_8));
    ac_int t_9 = math_log10(1000.0);
    printf("%lld\n", (long long)(t_9));
    ac_int t_10 = math_log2(1024.0);
    printf("%lld\n", (long long)(t_10));
    printf("%s\n", "--- Rounding ---");
    ac_int t_11 = math_floor(4.9);
    printf("%lld\n", (long long)(t_11));
    ac_int t_12 = math_ceil(4.1);
    printf("%lld\n", (long long)(t_12));
    ac_int t_13 = math_round(4.5);
    printf("%lld\n", (long long)(t_13));
    double t_15 = 0 - 7.3;
    ac_int t_14 = math_abs(t_15);
    printf("%lld\n", (long long)(t_14));
    printf("%s\n", "--- Clamp ---");
    ac_int t_16 = math_clamp(5.0, 0.0, 10.0);
    printf("%lld\n", (long long)(t_16));
    double t_18 = 0 - 3.0;
    ac_int t_17 = math_clamp(t_18, 0.0, 10.0);
    printf("%lld\n", (long long)(t_17));
    ac_int t_19 = math_clamp(15.0, 0.0, 10.0);
    printf("%lld\n", (long long)(t_19));
    printf("%s\n", "--- Conversions ---");
    ac_int t_20 = math_to_int(3.99);
    printf("%lld\n", (long long)(t_20));
    ac_int t_21 = math_to_dec(42);
    printf("%lld\n", (long long)(t_21));
    // <mainloop>
}
