/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include "library/ilib/gl/gl_c.h"
// Link: gcc output.c -L./library/ilib/gl -lacgl
#include "library/ilib/dynamic-resize/dynamic-resize_c.h"
// Link: gcc output.c -L./library/ilib/dynamic-resize -lacdynamic-resize
#include "library/ilib/math/math_c.h"
// Link: gcc output.c -L./library/ilib/math -lacmath

typedef long long ac_int;
typedef const char* ac_str;

int main()
{
}
