/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

typedef long long ac_int;
typedef const char* ac_str;

ac_int sieve(ac_int n) {
    ac_int prime[] = {};
    ac_int j = 0;
L0:;
    ac_int t0 = (ac_int)(j <= n);
    if (!(t0)) goto L1;
    prime_append(True);
    j = j + 1;
    goto L0;
L1:;
    prime[0] = 0;
    prime[1] = 0;
    ac_int p = 2;
L2:;
    ac_int t2 = p * p;
    ac_int t3 = (ac_int)(t2 <= n);
    if (!(t3)) goto L3;
    ac_int t4 = p + 1;
    ac_int t5 = t4 - 1;
    ac_int t6 = prime[t5];
    if (!(t6)) goto L4;
    ac_int i = p * p;
L6:;
    ac_int t8 = (ac_int)(i <= n);
    if (!(t8)) goto L7;
    ac_int t9 = i + 1;
    ac_int t10 = t9 - 1;
    prime[t10] = 0;
    i = i + p;
    goto L6;
L7:;
L4:;
    p = p + 1;
    goto L2;
L3:;
    ac_int result[] = {};
    i = 2;
L8:;
    ac_int t13 = (ac_int)(i <= n);
    if (!(t13)) goto L9;
    ac_int t14 = i + 1;
    ac_int t15 = t14 - 1;
    ac_int t16 = prime[t15];
    if (!(t16)) goto L10;
    result_append(i);
L10:;
    i = i + 1;
    goto L8;
L9:;
    return result;
}

int main()
{
    ac_int limit = 50;
    ac_int primes = sieve(limit);
    printf("%lld\n", (long long)(primes));
}
