/* Generated by AC Compiler (AC->C) */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include "library/ilib/widgets/widgets_c.h"
// Link: gcc output.c -L./library/ilib/widgets -lacwidgets

typedef long long ac_int;
typedef const char* ac_str;

ac_int OnClick(ac_int arg) {
    _exit(1);
}

int main()
{
    // <mainloop>
    ac_int root = Screen("AC Widget Demo", "480x520");
    ac_int title_lbl = display(root, "=== AC Widgets Library ===");
    ac_int name_lbl = display(root, "Your name:");
    ac_int name_inp = ask(root, 30);
    ac_int lang_lbl = display(root, "Favourite language:");
    ac_int lang_drop = dropdown(root);
    lang_drop_add("AC");
    lang_drop_add("Python");
    lang_drop_add("Rust");
    lang_drop_add("Go");
    ac_int agree_ck = ckbtn(root, "I agree to everything");
    ac_int volume = slider(root, 0, 100, "horizontal");
    ac_int bar = advance(root, 200);
    bar_set(42);
    ac_int result_lbl = display(root, "Result: (click Submit)");
    ac_int greet_btn = btn(root, "Submit", OnClick);
    root_mainloop();
    // <mainloop>
}
